[package]
name = "hopers-bet"
version = "0.1.0"
authors = [ "Deliver DAO" ]
edition = "2018"

[dependencies]
cosmwasm-std = "1.1.2"
cosmwasm-storage = "1.1.2"
cw-storage-plus = "0.15.0"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
partial_derive = { version = "0.1.0" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
